# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subindicator_text', models.CharField(max_length=200)),
                ('explanation_text', models.TextField()),
                ('datatype', models.CharField(choices=[(('B',), 'Binary'), (('D',), 'Decimal'), (('N',), 'None')], default=('N',), max_length=1)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Indicator')),
            ],
        ),
    ]
